name: Release

on:
  pull_request:
    paths:
      - 'HackathonBot/**'

  HackathonBot-build:
    name: ${{ matrix.friendlyName }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        PythonVersion: [ '3.10' ]
        os: [ macos-11, windows-2019 ]
        arch: [ x64, arm64 ]
        include:
          - os: macos-11
            friendlyName: macOS
            asset_name: HackathonBot-darwin
          - os: windows-2019
            friendlyName: Windows
            asset_name: HackathonBot-win32
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.PythonVersion }}
      - name: set environment variable
        run: |
          export ISSUSE_TOKEN=${{ ISSUSE_TOKEN }}
          export COMMENT_TOKEN=${{ COMMENT_TOKEN }}
          echo $ISSUSE_TOKEN
          echo $COMMENT_TOKEN
      - run: pip install requests schedule pyinstaller
      - name: PyInstaller build
        uses: sayyid5416/pyinstaller@main
        with:
          python_ver: ${{ matrix.PythonVersion }}
          exe_path: ./dist/${{ matrix.friendlyName }}
          spec: 'HackathonBot/build.spec'
          upload_exe_with_name: ${{ matrix.asset_name }}-${{ matrix.arch }}
          options: --windowed, --onefile